### ISSUE TITLE
Add UVC Driver on AGNOS Linux Kernel

### ISSUE THREAD

**Issue by jptalledo10** [commaai/agnos-builder#211] opened 2024-03-03 03:08 UTC
Hi

I am doing some experiments with UVC camera and need to compile the driver and relative USB support.

Can someone advise the environment setup so I can run make menuconfig, changes/add stuff and cross-compile the modules
to be loaded with insmod.

**Comment by adeebshihadeh** [comment] 2024-04-24 20:44
Closing as this is not a bug/issue; check out the community Discord for development discussion instead: https://discord.comma.ai.

**Closed by adeebshihadeh** 2024-04-24 20:44 UTC
