### ISSUE TITLE
System Reset dialog causes black screen  and/or prompts for reset after restart of service

### ISSUE THREAD

**Issue by devtekve** [commaai/agnos-builder#214] opened 2024-04-10 06:54 UTC
@adeebshihadeh this introduced a behavior where calling `sudo systemctl restart comma` would always bring up the system reset dialog. However, the reset dialog does not ask the screen to turn on if the screen is already off. Leading to a full black screen in those cases, and leading to an annoying reset prompt otherwise, because the count of taps is from device boot and never resets.

_Originally posted by @devtekve in https://github.com/commaai/agnos-builder/issues/203#issuecomment-2046657275_

**Comment by adeebshihadeh** [comment] 2024-04-11 21:50
Duplicate of #212

**Closed by adeebshihadeh** 2024-04-11 21:50 UTC
